Description of interpolate_bilinear
Home > 16-Surfacereconstruction > Functions > interpolate_bilinear.m
interpolate_bilinear
PURPOSE
% interpolate_bilinear
SYNOPSIS
function z=interpolate_bilinear(S,x,y,dx,BB,sigma_h);
DESCRIPTION
% interpolate_bilinear
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_smooth_dem_robust_bilinear % test dem smoothing
test_smooth_dem_robust_bilinear_square % test dem smoothing
fig_16_20_demo_surface_reconstruction % Fig. 16.20 page 761
fig_16_21_quality_surface_reconstruction % Fig. 16.21 theoretical quality of surface reconstruction
SOURCE CODE
%% interpolate_bilinear
function z=interpolate_bilinear(S,x,y,dx,BB,sigma_h);
x=(x-BB(1))/dx+1;
y=(y-BB(2))/dx+1;
xr=floor(x);
yr=floor(y);
s=x-xr;
t=y-yr;
z=(1-s)*(1-t)*S(xr,yr)...
  +s*(1-t)*S(xr+1,yr)...
  +(1-s)*t*S(xr,yr+1)...
  +s*t*S(xr+1,yr+1);
z=z*sigma_h;
[x-1,y-1,z,xr,yr,s,t,sqrt(S(xr,yr))*sigma_h];
return