Description of calc_Dual
Home > General-Functions > Geometry > calc_Dual.m
calc_Dual
PURPOSE
% dualizing matrix
SYNOPSIS
function D = calc_Dual
DESCRIPTION
% dualizing matrix
 Usage:
   D = calc_Dual
   D - 6x6 dualizing matrix
       [0 0 0 1 0 0
        0 0 0 0 1 0
        0 0 0 0 0 1
        1 0 0 0 0 0
        0 1 0 0 0 0
        0 0 1 0 0 0]
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 See also calc_Gamma, calc_Gammadual, calc_Gamma_reduced,
 calc_Gammadual_reduced, calc_Pi calc_Pidual
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_dual % DEMO Duality
demo_single_image_geometry % DEMO single image geometry
demo_singularity_line_through_four_lines % Test singularity of line through four lines
demo_selection_X_on_Li % test whether selection is necessary when using L through X constraint
demo_check_of_signs_single_and_two_view_geometry % demo: check of signs single and two view geometry
sugr_minimal_3D_Line % generate minimal representation for 3D homogeneous line
SOURCE CODE
%% dualizing matrix
%
% Usage:
%   D = calc_Dual
%
%   D - 6x6 dualizing matrix
%       [0 0 0 1 0 0
%        0 0 0 0 1 0
%        0 0 0 0 0 1
%        1 0 0 0 0 0
%        0 1 0 0 0 0
%        0 0 1 0 0 0]
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% See also calc_Gamma, calc_Gammadual, calc_Gamma_reduced,
% calc_Gammadual_reduced, calc_Pi calc_Pidual
function D = calc_Dual
D = [zeros(3,3),eye(3);
     eye(3),zeros(3,3)
    ];