Description of calc_S_reduced
Home > General-Functions > Geometry > calc_S_reduced.m
calc_S_reduced
PURPOSE
% Skew matrix with independent selected rows
SYNOPSIS
function [S , R] = calc_S_reduced(x)
DESCRIPTION
% Skew matrix with independent selected rows
 see PCV (7.120) ff
 Usage:
   [S,R] = calc_S_reduced(x)
   Ss - 2x3 skew matrix, reduced to independent rows
   Rm - 2x3 reduction matrix: Ss = Rm * S
 Wolfgang Förstner 02/2010
 wfoerstn@uni-bonn.de
 See also calc_S, calc_v_from_S
CROSS-REFERENCE INFORMATION
This function calls:
calc_S % skew matrix of 3-vector
This function is called by:
sugr_estimation_algebraic_Homography_2D_from_point_pairs % Algebraic estimation of 2D homography from point pairs,
sugr_ghm_cg_2D_homography_from_point_pairs % determines residuals etc. for 2D homography from point pairs
SOURCE CODE
%% Skew matrix with independent selected rows
% see PCV (7.120) ff
%
% Usage:
%   [S,R] = calc_S_reduced(x)
%
%   Ss - 2x3 skew matrix, reduced to independent rows
%   Rm - 2x3 reduction matrix: Ss = Rm * S
%
% Wolfgang Förstner 02/2010
% wfoerstn@uni-bonn.de
%
% See also calc_S, calc_v_from_S
function [S , R] = calc_S_reduced(x)
% select index with maximum |x|
[~,i] = max(abs(x));
% generate rselection matrix
switch i
    case 1
        R = [0 1 0;0 0 1];
    case 2
        R = [1 0 0;0 0 1];
    case 3
        R = [1 0 0;0 1 0];
end
% generate selected matrix
S = R *calc_S(x);