Description of calc_Gammadual
Home > General-Functions > Geometry > calc_Gammadual.m
calc_Gammadual
PURPOSE
% dual Plückermatrix from Plücker vector
SYNOPSIS
function G = calc_Gammadual (L)
DESCRIPTION
% dual Plückermatrix from Plücker vector
 see PCV (5.134)
 Usage
   G = calc_Gamma (L)
   L - 6x1 Plücker Line
   G - 4x1 dual Gamma Matrix / dual Plückermatrix
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 See also calc_Gamma, calc_Gamma_reduced, calc_Gammadual_reduced,
 calc_Pi, calc_Pidual, calc_Dual
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_3D_geometry % Demo 3D-geometry
demo_dual % DEMO Duality
demo_single_image_geometry % DEMO single image geometry
demo_selection_X_on_Li % test whether selection is necessary when using L through X constraint
demo_check_of_signs_single_and_two_view_geometry % demo: check of signs single and two view geometry
calc_Gammadual_reduced % reduced dual Plückermatrix from Plücker vector
calc_intersect_3D_Lines2Point % intersection point X of two coplanar 3D-lines L and M
SOURCE CODE
%% dual Plückermatrix from Plücker vector
% see PCV (5.134)
%
% Usage
%   G = calc_Gamma (L)
%
%   L - 6x1 Plücker Line
%   G - 4x1 dual Gamma Matrix / dual Plückermatrix
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% See also calc_Gamma, calc_Gamma_reduced, calc_Gammadual_reduced,
% calc_Pi, calc_Pidual, calc_Dual
function G = calc_Gammadual (L)
G= ...
[...
       0     L(3) -L(2) -L(4); ...
      -L(3)  0     L(1) -L(5); ...
       L(2) -L(1)  0    -L(6); ...
       L(4)  L(5)  L(6)  0 ...
];