Description of calc_Rot_ab
Home > General-Functions > Geometry > calc_Rot_ab.m
calc_Rot_ab
PURPOSE
% minimum Rotation matrix from vector a to vector b
SYNOPSIS
function R = calc_Rot_ab(a,b)
DESCRIPTION
% minimum Rotation matrix from vector a to vector b
 see PCV (8.76)
 Usage:
   R = calc_Rot_ab(a,b)
   a,b - double DX1, pair of noncoplanar vectors
   R - double DxD, rotation matrix
 Wolfgang Förstner 1/2011
 wfoerstn@uni-bonn.de
 See also calc_R_from_opq_kraus, calc_opq_from_R_Kraus, calc_Rot_q,
 calc_Rot_r, calc_Rot_rod, calc_Rot_rp, calc_Mq, calc_Mq_comm, calc_r_phi_from_R
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sugr_ghm_cg_E_matrix_from_point_pairs % Constraints and Jacobians for GHM for estimating E-matrix from point pairs
sugr_ghm_cg_2D_homography_from_point_pairs % determines residuals etc. for 2D homography from point pairs
sugr_ghm_cg_Plane_from_points % determines residuals etc. for estimating plane from points
sugr_construct_mean_Point_2D sugr_construct_mean_Point_2D: mid point of two 2D points
sugr_ghm_cg_Point_2D_from_Lines % Determines residuals etc. for 2D point from passing lines
sugr_ghm_cg_Projection_3D_2D_from_point_pairs % Determines residuals etc. for projection from point pairs
SOURCE CODE
%% minimum Rotation matrix from vector a to vector b
% see PCV (8.76)
%
% Usage:
%   R = calc_Rot_ab(a,b)
%
%   a,b - double DX1, pair of noncoplanar vectors
%   R - double DxD, rotation matrix
%
% Wolfgang Förstner 1/2011
% wfoerstn@uni-bonn.de
%
% See also calc_R_from_opq_kraus, calc_opq_from_R_Kraus, calc_Rot_q,
% calc_Rot_r, calc_Rot_rod, calc_Rot_rp, calc_Mq, calc_Mq_comm, calc_r_phi_from_R
function R = calc_Rot_ab(a,b)
as = a/norm(a);
bs = b/norm(b);
R = eye(length(a))+2*bs*as'-(as+bs)*(as+bs)'/(1+as'*bs);