Description of calc_Pi
Home > General-Functions > Geometry > calc_Pi.m
calc_Pi
PURPOSE
% Pi-matrix from 3D-point 4-vector
SYNOPSIS
function P = calc_Pi(X)
DESCRIPTION
% Pi-matrix from 3D-point 4-vector
 see PCV (7.37)
 Usage
   P = calc_Pi (X)
   X - 4x1 homogeneous 3D point
   P - 6x4 Pi Matrix
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 See also calc_Pidual, calc_Gamma, calc_Gammadual, calc_Gamma_reduced,
 calc_Gammadual_reduced, calc_Dual
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_3D_Lines2Point % Demo intersection and join of 3D lines
demo_3D_Points_distances % demo distanc 3D point
demo_3D_geometry % Demo 3D-geometry
demo_dual % DEMO Duality
demo_singularity_line_through_four_lines % Test singularity of line through four lines
demo_estimate_two_symmetric_planes_from_points % test_two_symmetric_planes_from_points
demo_selection_X_on_Li % test whether selection is necessary when using L through X constraint
demo_check_of_signs_single_and_two_view_geometry % demo: check of signs single and two view geometry
calc_Q_from_P % calculates projection matrix Q for lines from P
SOURCE CODE
%% Pi-matrix from 3D-point 4-vector
% see PCV (7.37)
%
% Usage
%   P = calc_Pi (X)
%
%   X - 4x1 homogeneous 3D point
%   P - 6x4 Pi Matrix
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% See also calc_Pidual, calc_Gamma, calc_Gammadual, calc_Gamma_reduced,
% calc_Gammadual_reduced, calc_Dual
function P = calc_Pi(X)
P= ...
[...
      X(4)  0     0    -X(1); ...
      0     X(4)  0    -X(2); ...
      0     0     X(4) -X(3); ...
      0    -X(3)  X(2)  0; ...
      X(3)  0    -X(1)  0; ...
     -X(2)  X(1)  0     0  ...
];