Description of calc_Rot_r
Home > General-Functions > Geometry > calc_Rot_r.m
calc_Rot_r
PURPOSE
% Cayley rotation matrix
SYNOPSIS
function R = calc_Rot_r(r)
DESCRIPTION
% Cayley rotation matrix
 R = (I-S_r)^-1*(I+S_r)
 see PCV (8.62)
 Usage:
   R = calc_Rot_r(r)
   r - double 3x1
   R - double 3x3, 3D rotation matrix (rotates by 2|r|)
 Wolfgang Förstner 10/2011
 wfoerstn@uni-bonn.de
 See also calc_R_from_opq_kraus, calc_r_phi_from_R, calc_Rot_ab,
 calc_Rot_q, calc_Rot_rod, calc_Rot_rp, calc_Mq, calc_Mq_comm, calc_opq_from_R_Kraus
CROSS-REFERENCE INFORMATION
This function calls:
calc_S % skew matrix of 3-vector
This function is called by:
demo_single_image_geometry % DEMO single image geometry
demo_direct_plane_fit % demo plane fitting direct method
demo_bR_from_UVuv % demo: bR from (U,V,xs,xss)
demo_estimate_E_Matrix_from_point_pairs % test_estimate_E_Matrix_from_point_pairs
demo_triangulation_spherical % demo triangulation
example_p_579_relative_orientation_mirror % test mirror image
demo_sugr_E_matrix % test sugr_E_matrix
e_from_bR % get e (= vec E) from [db_r,dr]
SOURCE CODE
%% Cayley rotation matrix
% R = (I-S_r)^-1*(I+S_r)
% see PCV (8.62)
%
% Usage:
%   R = calc_Rot_r(r)
%
%   r - double 3x1
%   R - double 3x3, 3D rotation matrix (rotates by 2|r|)
%
% Wolfgang Förstner 10/2011
% wfoerstn@uni-bonn.de
%
% See also calc_R_from_opq_kraus, calc_r_phi_from_R, calc_Rot_ab,
% calc_Rot_q, calc_Rot_rod, calc_Rot_rp, calc_Mq, calc_Mq_comm, calc_opq_from_R_Kraus
function R = calc_Rot_r(r)
R = inv(eye(3)-calc_S(r))*(eye(3)+calc_S(r));                               %#ok<MINV>