Description of calc_S
Home > General-Functions > Geometry > calc_S.m
calc_S
PURPOSE
% skew matrix of 3-vector
SYNOPSIS
function S = calc_S(x)
DESCRIPTION
% skew matrix of 3-vector
 see PCV (A.34)
 Usage:
   S = calc_S(x)
   x - 3x1 vector
   S - 3x3 skew matrix
 let x = [a b c], than
     S = [  0 -c  b |
         | -c  0 -a |
         | -b  a  0 ]
 Wolfgang Förstner 1/2011
 wfoerstn@uni-bonn.de
 See also calc_S_reduced, calc_v_from_S
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_2D_geometry % DEMO 2D projective geometry
demo_bR_from_UVuv % demo: bR from (U,V,xs,xss)
example_p_579_relative_orientation_mirror % test mirror image
calc_Rot_r % Cayley rotation matrix
calc_Rot_rp % Rotation matrix from axis and angle
calc_S_reduced % Skew matrix with independent selected rows
calc_distance_3D_point_from_3D_line % distance 3D point from 3D line
plot_2D_line % plots a 2D line from homogeneous vector h [3x1]
e_from_bR % get e (= vec E) from [db_r,dr]
sugr_CovM_E_matrix % Covariance matrix of parameters of essential matrix
sugr_E_Matrix % create E-matrix
sugr_bR_from_UVuv % Determine bR from (U,V,u,v
sugr_estimation_ml_E_Matrix_from_point_pairs % ML estimation of E-Matrix from point pairs
sugr_get_CbRbR_JebR_from_b_R_Cee % Determine CbRbR from Cee for given Relative Orientaion
sugr_get_Cee_JebR_from_b_R_CbRbR % Determine Cee from CbRbR for given Relative Orientaion
sugr_ghm_cg_E_matrix_from_point_pairs % Constraints and Jacobians for GHM for estimating E-matrix from point pairs
sugr_select_bR_from_E_UV_uv % Select bR from E
sugr_triangulate_two_spherical_cameras % sugr_triangulate_two_spherical_cameras
sugr_estimate_F_and_epipoles_algebraically % Algebraic estimate F-matrix and epipoles: from n > 7 points
sugr_ghm_update_E_Matrix % GHM update params relative orientation/E-matrix
sugr_estimation_algebraic_Homography_2D_from_point_pairs % Algebraic estimation of 2D homography from point pairs,
sugr_ghm_cg_2D_homography_from_point_pairs % determines residuals etc. for 2D homography from point pairs
sugr_construct_join_Line_2D % Construct 2D line joining two points x and y
sugr_construct_midline_Line_2D % Construct midline of two 2D points x and y
sugr_construct_parallel_lx_Line_2D % Construct 2D line parallel to line l through point x
sugr_construct_footpoint_Ol_Point_2D % Foot point from 2D origin O to uncertain line l
sugr_construct_footpoint_xl_Point_2D % Foot point from Point_2D x onto line l
sugr_construct_intersection_Point_2D % Intersection 2D point two lines l and m
sugr_estimation_algebraic_Projection_3D_2D_from_point_pairs % Algebraic estimate of Projection from corresponding 3D-2D point pairs
sugr_cov_matr_X % determine CovM for triangulated point (cov_matr_X)
SOURCE CODE
%% skew matrix of 3-vector
% see PCV (A.34)
%
% Usage:
%   S = calc_S(x)
%
%   x - 3x1 vector
%   S - 3x3 skew matrix
%
% let x = [a b c], than
%     S = [  0 -c  b |
%         | -c  0 -a |
%         | -b  a  0 ]
%
% Wolfgang Förstner 1/2011
% wfoerstn@uni-bonn.de
%
% See also calc_S_reduced, calc_v_from_S
function S = calc_S(x)
S = [...
     0    -x(3)  x(2);...
     x(3)    0  -x(1);...
    -x(2)  x(1)    0 ...
    ];