Description of calc_Q_from_P
Home > General-Functions > Geometry > calc_Q_from_P.m
calc_Q_from_P
PURPOSE
% calculates projection matrix Q for lines from P
SYNOPSIS
function Q = calc_Q_from_P (P)
DESCRIPTION
% calculates projection matrix Q for lines from P
 see PCV (12.71)
 Usage:
   Q = calc_Q_from_P (P)
   P - 4 x 3-projection matrix P = K*R*[I|-Z]
   Q - 3x6 projection matrix for lines
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 See also calc_P_from_KRZ, calc_KRZ_from_P, calc_viewing_direction
CROSS-REFERENCE INFORMATION
This function calls:
calc_Pi % Pi-matrix from 3D-point 4-vector
This function is called by:
demo_single_image_geometry % DEMO single image geometry
demo_check_of_signs_single_and_two_view_geometry % demo: check of signs single and two view geometry
SOURCE CODE
%% calculates projection matrix Q for lines from P
% see PCV (12.71)
%
% Usage:
%   Q = calc_Q_from_P (P)
%
%   P - 4 x 3-projection matrix P = K*R*[I|-Z]
%   Q - 3x6 projection matrix for lines
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% See also calc_P_from_KRZ, calc_KRZ_from_P, calc_viewing_direction
function Q = calc_Q_from_P (P)
A=P(1,:)';
B=P(2,:)';
C=P(3,:)';
Q=[(calc_Pi(B) * C)'; ...
   (calc_Pi(C) * A)'; ...
   (calc_Pi(A) * B)'];