Description of plot_circle
Home > General-Functions > Graphics > plot_circle.m
plot_circle
PURPOSE
% plot circle.
SYNOPSIS
function h = plot_circle(xo,yo,r, fmt, varargin)
DESCRIPTION
% plot circle.
 Usage:
    plot_circle( xo,yo,r, fmt)
 xo,yo: centre
     r: radius
   fmt: format string
 author J. meidow, FGAN-FOM
 2004, Oct:  initial code
 2005, Jan.: varargs and doc. added
CROSS-REFERENCE INFORMATION
This function calls:
plot_ellipse % plot_ellipse: plot 2D ellipse
This function is called by:
demo_GHM_similarity % GHM with similarity
fig_4_11_test_sensitivity_factors_GMM_similarity % Fig. 4.11 test sensitivity factors in GMM with similarity
SOURCE CODE
%% plot circle.
%
% Usage:
%    plot_circle(xo,yo,r, fmt)
%
% xo,yo: centre
%     r: radius
%   fmt: format string
%
% author J. meidow, FGAN-FOM
%
% 2004, Oct:  initial code
% 2005, Jan.: varargs and doc. added
function h = plot_circle(xo,yo,r, fmt, varargin)
if r > 0.0
    h = plot_ellipse([xo,yo,r,r,0.0],fmt);
    if nargin>4
        set(h,varargin{:});
    end
end