Description of plot_square_with_background
Home > General-Functions > Graphics > plot_square_with_background.m
plot_square_with_background
PURPOSE
% plot box with background
SYNOPSIS
function plot_square_with_background(x,y,w,f1,f2)
DESCRIPTION
% plot box with background
 Usage:
   plot_square_with_background(x,y,w);
 x,y:  position
 w: sidelength
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
determine_Homography_2D_from_two_images demo_h_determine_homography_from_two_images: read/interactively determine homography
h_plot_CP plot control points
h_transfer_grid demo_h_transfer_grid: transfer point in demo_homography
h_transfer_points demo_h_transfer_points: transfer point in demo_homography
demo_epipolar_geometry % Epipolar geometry
measure_homologeous_Points This function enables the user to measure homologous points in two
SOURCE CODE
%% plot box with background
%
% Usage:
%   plot_square_with_background(x,y,w);
%
% x,y:  position
% w: sidelength
function plot_square_with_background(x,y,w,f1,f2)
if nargin < 4
    f1 = 4;
    f2 = 2;
end
hi = w/2;
ho = hi;
plot([x-hi,x-hi,x+hi,x+hi,x-hi],[y-hi,y+hi,y+hi,y-hi,y-hi],'-k','Linewidth',f1);
plot([x-ho,x-ho,x+ho,x+ho,x-ho],[y-ho,y+ho,y+ho,y-ho,y-ho],'-y','Linewidth',f2);