Description of plot_init
Home > General-Functions > Graphics > plot_init.m
plot_init
PURPOSE
% plot_init: initialize visualization
SYNOPSIS
function varargout = plot_init
DESCRIPTION
% plot_init: initialize visualization
 usage: plot_init
             set Latex as default interpreter for all text props
        screensize = plot_init
             set Latex as default interpreter for all text props and
             return screensize: 1x2 int, size of current screen [width, height]
 Susane Wenzel 09/16
 wenzel@igg.uni-bonn.de
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_plot_histogram_with_theoretical_density % plot histogram with theoretical density function
fig_2_10_demo_AR_process % Fig. 2.10 page 54
fig_2_11_demo_scatter_histogram % Fig. 2.11 page 56
fig_2_9_simulate_hom_profiles_gaussian % Fig. 2.9 page 51 and Fig 16.11 page 742
demo_GHM_2D_line % Demo nonlinear GHM without constraints
demo_GHM_similarity % GHM with similarity
demos_GMM_regression % test GMM with linear regression with check
fig_4_11_test_sensitivity_factors_GMM_similarity % Fig. 4.11 test sensitivity factors in GMM with similarity
demo_2D_geometry % DEMO 2D projective geometry
demo_3D_Points_distances % demo distanc 3D point
demo_estimate_2D_homography_from_point_pairs % demo_estimate_2D_homography_from_point_pairs
demo_construct_Line_2D % test_construct_Line_2D: test routine for constructing 2D lines
demo_sugr_Line_2D demo_sugr_Line_2D: demo routine for creating a 2D lines
demo_construct_Point_2D demo_construct_Point_2D
demo_estimate_Point_2D_from_Lines % demo_estimate_Point_2D_from_Lines
demo_sugr_Point_2D demo_sugr_Point_2D: demo routine for generating 2D point
determine_Homography_2D_from_two_images demo_h_determine_homography_from_two_images: read/interactively determine homography
h_transfer_grid demo_h_transfer_grid: transfer point in demo_homography
demo_estimate_two_symmetric_planes_from_points % test_two_symmetric_planes_from_points
demo_ALG_17_estimate_Projection_3D_2D_from_point_pairs % Demo estimate 3D projection from 2D point pairs, ALG 17
demo_estimate_Projection_3D_2D_from_point_pairs_single % Demo estimate 3D projection from 2D point pairs
demo_estimate_E_Matrix_from_point_pairs % test_estimate_E_Matrix_from_point_pairs
demo_triangulation_spherical % demo triangulation
demo_epipolar_geometry % Epipolar geometry
fig_16_11_simulate_inhom_profiles_gaussian % Fig. 2.9 page 51 and Fig 16.11 page 742
fig_16_13_profile_reconstruction_demo_precision % Fig 16.13 page 750
fig_16_14_test_scale % Fig. 16.14 page 754
fig_16_15_symmetric_outliers % Fig. 16.15 page 755
fig_16_16_plot_weight_functions_asymmetric % Fig. 16.16 page 756
fig_16_17_asymmetric_outliers % Fig. 16.17 page 756
fig_16_18_step_break % Fig. 15.18 page 758
fig_16_3_16_4_example_demo_profile % Fig. 16.3 page 731 and 16.4 page 732
fig_16_9_demo_profile_reconstruction % Fig. 16.9 page 740
simulate_points_dem_10 % read ply-file
simulate_points_dem_16_precision % generate a set of points for dem-precision analysis
simulate_points_dem_6 % simulate_points_dem_6: generate test image of Uwe 1994
eq_15_120_theoretical_accuracy % eq_15_120_theoretical accuracy
fig_16_20_demo_surface_reconstruction % Fig. 16.20 page 761
fig_16_21_quality_surface_reconstruction % Fig. 16.21 theoretical quality of surface reconstruction
fig_16_22_demo_robust_surface_reconstruction % Fig. 16.22 page 762
fig_16_23_aurelo_result % Fig. 16.23 page 764
fig_16_9b_demo_surface_reconstruction % Fig. 16.9 bottom page 740
sugr_perturb_3D_2D_point_pairs % Perturb sampled 3D 2D points pairs
check_estimation_result % check estimation result, PCV Sect. 4.6.8
SOURCE CODE
%% plot_init: initialize visualization
%
% usage: plot_init
%             set Latex as default interpreter for all text props
%        screensize = plot_init
%             set Latex as default interpreter for all text props and
%             return screensize: 1x2 int, size of current screen [width, height]
%
% Susane Wenzel 09/16
% wenzel@igg.uni-bonn.de
function varargout = plot_init
if verLessThan('matlab', '8')
else
%     set Latex as default interpreter for all text props
    set(0, 'defaulttextinterpreter','latex');
    set(0, 'defaultAxesTickLabelInterpreter','latex');
    set(0, 'defaultLegendInterpreter','latex');
end
if nargout==1
    % get current screensize, for proper positioning of figures
    screensize = get(0,'ScreenSize'); screensize = screensize(3:4);
    varargout = {screensize};
end