Description of sugr_plot_Point_2D
Home > General-Functions > SUGR > Point_2D > sugr_plot_Point_2D.m
sugr_plot_Point_2D
PURPOSE
% Plot 2D point with standard ellipse
SYNOPSIS
function sugr_plot_Point_2D(x,center_type,bound_type,lw,factor)
DESCRIPTION
% Plot 2D point with standard ellipse
 sugr_plot_Point_2D(x,center_type,bound_type,lw,factor)
 * x      = geometric element
 * center_type   = type of plotting the element
 * bound_type    = type of plotting the confidence region
 * lw      = linewidth
 * factor  = magnification factor
 Wolfgang Förstner 1/2011
 wfoerstn@uni-bonn.de
 sw 9/2016
 See also sugr_Point_2D
CROSS-REFERENCE INFORMATION
This function calls:
adjunctMatrix % determines adjunct matrix for a square matrix
sugr_get_CovM_homogeneous_Vector % get CovM of homogeneous vector x.h
sugr_plot_conic_explicit % explicit plot of conic (ellipse or hyperbola)
sugr_get_isfinite_Point_2D % Test whether 2D point is finite
This function is called by:
demo_construct_Line_2D % test_construct_Line_2D: test routine for constructing 2D lines
demo_construct_Point_2D demo_construct_Point_2D
demo_estimate_Point_2D_from_Lines % demo_estimate_Point_2D_from_Lines
demo_sugr_Point_2D demo_sugr_Point_2D: demo routine for generating 2D point
h_transfer_grid demo_h_transfer_grid: transfer point in demo_homography
h_transfer_points demo_h_transfer_points: transfer point in demo_homography
demo_epipolar_geometry % Epipolar geometry
sugr_plot_Homography_2D % plot uncertain homography 2D
sugr_perturb_2D_point_pairs % Perturb sampled 2D points pairs
sugr_perturb_2D_point_pairs_spherical % Perturb sampled 2D points pairs sphericaly
sugr_perturb_3D_2D_point_pairs % Perturb sampled 3D 2D points pairs
SOURCE CODE
%% Plot 2D point with standard ellipse
%
% sugr_plot_Point_2D(x,center_type,bound_type,lw,factor)
%
% * x      = geometric element
% * center_type   = type of plotting the element
% * bound_type    = type of plotting the confidence region
% * lw      = linewidth
% * factor  = magnification factor
%
% Wolfgang Förstner 1/2011
% wfoerstn@uni-bonn.de
%
% sw 9/2016
%
% See also sugr_Point_2D
function sugr_plot_Point_2D(x,center_type,bound_type,lw,factor)
if nargin < 4
    lw=2;
end
if nargin < 5
    factor=1;
end
if sugr_get_isfinite_Point_2D(x) % only finite elements
    Chh = sugr_get_CovM_homogeneous_Vector(x);
    C   = adjunctMatrix(Chh-x.h*x.h');
    sugr_plot_conic_explicit(C,center_type,bound_type,lw,factor);
end