Description of sugr_Point_2D
Home > General-Functions > SUGR > Point_2D > sugr_Point_2D.m
sugr_Point_2D
PURPOSE
% Create 2D point
SYNOPSIS
function Point_2D = sugr_Point_2D(a1,a2,a3,a4)
DESCRIPTION
% Create 2D point
 Usage:
    Point_2D = sugr_Point_2D(xe)
         Euclidean vector, CovM = 0
    Point_2D = sugr_Point_2D(xh)
         homogeneous vector, CovM = 0
    Point_2D = sugr_Point_2D(x,y)
         Euclidean coordinates, CovM = 0
   Point_2D = sugr_Point_2D(xe,Cee)
         Euclidean vector with Cov.matrix
    Point_2D = sugr_Point_2D(xh,Chh)
          homgeneous vector with Cov.matrix
    Point_2D = sugr_Point_2D(u,v,w)
         homogeneous coordinates, CovM = 0
    Point_2D = sugr_Point_2D(x,y,Cee)
         Euclidean coordinates with Euclidean Cov.matrix
    Point_2D = sugr_Point_2D(x,y,sx,sy)
         independent Euclidean coordinates with standard deviations
    Point_2D = sugr_Point_2D(u,v,w,Chh)
         homogeneous coordinates with homogeneous Cov.matrix
  * Point_2D = structure
        .h    = spherically normalized homogeneous coordinates
        .Crr  = reducedcovariance matrix
        .Jr   = null space of .h'
        .type = 1
 Wolfgang Förstner 1/2011
 wfoerstn@uni-bonn.de
 See also sugr_Line_2D, sugr_Line_3D, sugr_Plane_3D, sugr_Point_3D
CROSS-REFERENCE INFORMATION
This function calls:
sugr_minimal_vector % generate minimal representation for homogeneous vector
This function is called by:
demo_construct_Line_2D % test_construct_Line_2D: test routine for constructing 2D lines
demo_construct_Point_2D demo_construct_Point_2D
demo_estimate_Point_2D_from_Lines % demo_estimate_Point_2D_from_Lines
demo_sugr_Point_2D demo_sugr_Point_2D: demo routine for generating 2D point
determine_Homography_2D_from_two_images demo_h_determine_homography_from_two_images: read/interactively determine homography
h_transfer_grid demo_h_transfer_grid: transfer point in demo_homography
h_transfer_points demo_h_transfer_points: transfer point in demo_homography
demo_estimate_two_symmetric_planes_from_points % test_two_symmetric_planes_from_points
demo_epipolar_geometry % Epipolar geometry
sugr_condition_Points % condition points, determine conditioning matrix
sugr_uncondition_Points % Uncondition points
sugr_plot_Homography_2D % plot uncertain homography 2D
sugr_transform_with_Homography_2D % transform uncertain elements using a projective mapping
sugr_construct_footpoint_Ol_Point_2D % Foot point from 2D origin O to uncertain line l
sugr_construct_intersection_Point_2D % Intersection 2D point two lines l and m
sugr_construct_mean_Point_2D sugr_construct_mean_Point_2D: mid point of two 2D points
sugr_construct_midpoint_Point_2D % Mid point of two 2D points
sugr_estimation_algebraic_Point_2D_from_Lines % Algebraic estimate of intersection Point_2D from N Lines_2D
sugr_estimation_geometric_Point_2D_from_Lines % Geometric estimate of intersection Point_2D from N Lines_2D
sugr_estimation_ml_Point_2D_from_Lines % ML estimate of intersection Point_2D from N Lines_2D
sugr_estimation_ml_Point_2D_from_Lines_Hessian % ML estimate of intersection Point_2D from N Lines_2D
sugr_perturb_2D_point_pairs % Perturb sampled 2D points pairs
sugr_perturb_2D_point_pairs_spherical % Perturb sampled 2D points pairs sphericaly
sugr_perturb_3D_2D_point_pairs % Perturb sampled 3D 2D points pairs
SOURCE CODE
%% Create 2D point
%
% Usage:
%    Point_2D = sugr_Point_2D(xe)
%         Euclidean vector, CovM = 0
%
%    Point_2D = sugr_Point_2D(xh)
%         homogeneous vector, CovM = 0
%
%    Point_2D = sugr_Point_2D(x,y)
%         Euclidean coordinates, CovM = 0
%
%   Point_2D = sugr_Point_2D(xe,Cee)
%         Euclidean vector with Cov.matrix
%
%    Point_2D = sugr_Point_2D(xh,Chh)
%          homgeneous vector with Cov.matrix
%
%    Point_2D = sugr_Point_2D(u,v,w)
%         homogeneous coordinates, CovM = 0
%
%    Point_2D = sugr_Point_2D(x,y,Cee)
%         Euclidean coordinates with Euclidean Cov.matrix
%
%    Point_2D = sugr_Point_2D(x,y,sx,sy)
%         independent Euclidean coordinates with standard deviations
%
%    Point_2D = sugr_Point_2D(u,v,w,Chh)
%         homogeneous coordinates with homogeneous Cov.matrix
%
%  * Point_2D = structure
%        .h    = spherically normalized homogeneous coordinates
%        .Crr  = reducedcovariance matrix
%        .Jr   = null space of .h'
%        .type = 1
%
% Wolfgang Förstner 1/2011
% wfoerstn@uni-bonn.de
%
% See also sugr_Line_2D, sugr_Line_3D, sugr_Plane_3D, sugr_Point_3D
function Point_2D = sugr_Point_2D(a1,a2,a3,a4)
% default
Chh  = zeros(3);
switch nargin
    case 0
    case 1 % 2- or 3-vector
        size_a1 = size(a1,1);
        switch size_a1
            case 2
%% (1) Euclidean vector, CovM == 0
                % spherically normalized
                Point_2D = sugr_minimal_vector([a1;1],Chh);
            case 3
%% (1) homogeneous vector, CovM == 0
                Point_2D = sugr_minimal_vector(a1,Chh);
        end
    case 2
        size_a2 = size(a1,1);
        switch size_a2
            case 1
%% (2) Euclidean coordinates, CovM == 0
                Point_2D = sugr_minimal_vector([a1;a2;1],Chh);
            case 2
%% (2) Euclidean vector
                % spehrically normalized
                Point_2D = sugr_minimal_vector([a1;1],[a2 zeros(2,1); zeros(1,3)]);
            case 3
%% (3) uncertain homogeneous coordinates
                Point_2D   = sugr_minimal_vector(a1,a2);
        end
    case 3
        size_a3 = size(a3,1);
        switch size_a3
            case 1
%% (3) homogeneous vector, CovM == 0
                 % spehrically normalized
                Point_2D = sugr_minimal_vector([a1;a2;a3],Chh);
            case 2
%% (3) Euclidean coordinates
                % spehrically normalized
                Point_2D = sugr_minimal_vector([a1;a2;1],[a3 zeros(2,1); zeros(1,3)]);
        end
    case 4
        size_a4 = size(a4,1);
        switch size_a4
            case 1
%% (4) Euclidean vector, independent coordinates
                % spehrically normalized
                Point_2D = sugr_minimal_vector([a1;a2;1],...
                           [ a3^2, 0, 0; 0, a4^2, 0; zeros(1,3)]);
            case 3
%% (4) homogeneous coordinates
                % spehrically normalized
                Point_2D = sugr_minimal_vector([a1;a2;a3],a4);
        end
end
Point_2D.Jr = null(Point_2D.h');
Point_2D.type=1;