Description of sugr_get_Euclidean_Point_2D
Home > General-Functions > SUGR > Point_2D > sugr_get_Euclidean_Point_2D.m
sugr_get_Euclidean_Point_2D
PURPOSE
% Get Euclidean coordinates with CovM
SYNOPSIS
function [e,Cee] = sugr_get_Euclidean_Point_2D(x)
DESCRIPTION
% Get Euclidean coordinates with CovM
 [e,Cee] = sugr_get_Euclidean_Point_2D(x)
 if finite point:
    e   = Euclidean coordinates
    Cee = CovM of e
 else zeros
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 wf 1/2011
 See also sugr_Point_2D, sugr_get_Euclidean_Line_2D,
 sugr_get_Euclidean_Point_3D, sugr_get_isfinite_Point_2D
CROSS-REFERENCE INFORMATION
This function calls:
sugr_get_isfinite_Point_2D % Test whether 2D point is finite
This function is called by:
demo_estimate_Point_2D_from_Lines % demo_estimate_Point_2D_from_Lines
demo_epipolar_geometry % Epipolar geometry
sugr_Homography_2D % create 2D homography
sugr_plot_Homography_2D % plot uncertain homography 2D
sugr_show_Point_2D % Show information of 2D point on console
SOURCE CODE
%% Get Euclidean coordinates with CovM
%
% [e,Cee] = sugr_get_Euclidean_Point_2D(x)
%
% if finite point:
%    e   = Euclidean coordinates
%    Cee = CovM of e
% else zeros
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
% wf 1/2011
%
% See also sugr_Point_2D, sugr_get_Euclidean_Line_2D,
% sugr_get_Euclidean_Point_3D, sugr_get_isfinite_Point_2D
function [e,Cee] = sugr_get_Euclidean_Point_2D(x)
switch sugr_get_isfinite_Point_2D(x)
    case 0
        e   = zeros(2,1);
        Cee = zeros(2,2);
    case 1
        e   = x.h(1:2)/x.h(3);
        J   =  1/x.h(3) * [eye(2) -x.h(1:2)/x.h(3)] * null(x.h');
        Cee = J * squeeze(x.Crr)  * J';
end