Description of sugr_get_isfinite_Line_2D
Home > General-Functions > SUGR > Line_2D > sugr_get_isfinite_Line_2D.m
sugr_get_isfinite_Line_2D
PURPOSE
% Test whether 2D line is finite
SYNOPSIS
function f = sugr_get_isfinite_Line_2D(l)
DESCRIPTION
% Test whether 2D line is finite
 f = sugr_get_isfinite_Line_2D(l)
 * l    = 2D line struct {l.h,l.Crr}
 * f    = boolean, true if l is finite, false otherwise
 Wolfgang Förstner 1/2011
 wfoerstn@uni-bonn.de
 See also sugr_Line_2D
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sugr_angle_Line_2D % Get angle between two 2D lines
sugr_get_Euclidean_Line_2D % Determines Hessian paramters of 2D line
sugr_plot_Line_2D % Plot uncertain 2D line with standard hyperbola
sugr_show_Line_2D % Show/print all representations of 2D line on console
SOURCE CODE
%% Test whether 2D line is finite
%
% f = sugr_get_isfinite_Line_2D(l)
%
% * l    = 2D line struct {l.h,l.Crr}
% * f    = boolean, true if l is finite, false otherwise
%
% Wolfgang Förstner 1/2011
% wfoerstn@uni-bonn.de
%
% See also sugr_Line_2D
function f = sugr_get_isfinite_Line_2D(l)
global Threshold_Euclidean_Normalization
f   =   norm(l.h(1:2)) > ...
                Threshold_Euclidean_Normalization * abs(l.h(3));