Description of sugr_construct_join_Line_2D
Home > General-Functions > SUGR > Line_2D > sugr_construct_join_Line_2D.m
sugr_construct_join_Line_2D
PURPOSE
% Construct 2D line joining two points x and y
SYNOPSIS
function Line_2D = sugr_construct_join_Line_2D(x,y)
DESCRIPTION
% Construct 2D line joining two points x and y
 Line_2D = sugr_construct_join_Line_2D(x,y)
 * x,y =  2D points, struct {x.h,x.Crr}
 * Line_2D =  2D line, struct {l.h,l.Crr}
CROSS-REFERENCE INFORMATION
This function calls:
calc_S % skew matrix of 3-vector
sugr_get_CovM_homogeneous_Vector % get CovM of homogeneous vector x.h
sugr_Line_2D % create homogeneous 2D line
This function is called by:
demo_construct_Line_2D % test_construct_Line_2D: test routine for constructing 2D lines
sugr_perturb_2D_point_pairs % Perturb sampled 2D points pairs
sugr_perturb_2D_point_pairs_spherical % Perturb sampled 2D points pairs sphericaly
SOURCE CODE
%% Construct 2D line joining two points x and y
%
% Line_2D = sugr_construct_join_Line_2D(x,y)
%
% * x,y =  2D points, struct {x.h,x.Crr}
% * Line_2D =  2D line, struct {l.h,l.Crr}
% Wolfgang Förstner 1/2011
% wfoerstn@uni-bonn.de
%
% See also sugr_Line_2D, sugr_construct_parallel_lx_Line_2D,
% sugr_construct_parallel_lO_Line_2D, sugr_construct_midline_Line_2D,
% sugr_construct_footpoint_Ol_Point_2D, sugr_construct_footpoint_xl_Point_2D,
% sugr_construct_join_Line_3D
function Line_2D = sugr_construct_join_Line_2D(x,y)
        Sx =   calc_S(x.h);
        Sy = - calc_S(y.h);
        h   = Sx * y.h;
        Cxhh = sugr_get_CovM_homogeneous_Vector(x);
        Cyhh = sugr_get_CovM_homogeneous_Vector(y);
        Chh = Sx * Cyhh * Sx' + Sy * Cxhh * Sy';
% generate line
Line_2D = sugr_Line_2D(h,Chh);