Description of sugr_get_centroid_Line_2D
Home > General-Functions > SUGR > Line_2D > sugr_get_centroid_Line_2D.m
sugr_get_centroid_Line_2D
PURPOSE
% Centroid representation from minimal representation
SYNOPSIS
function [x0,p,sp,sq] = sugr_get_centroid_Line_2D(l)
DESCRIPTION
% Centroid representation from minimal representation
 [x0,p,sp,sq] = sugr_get_centroid_Line_2D(l)
 * l     = 2D line struct, minimal representation {l.h,l.Crr}
 * x0 = centroid, [x-coord. y-coord.]'
 * p  = direction of normal
 * sp = standard deviation of normal direction
 * sq = standard deviation across line
 Jochen Meidow, Wolfgang Förstner
 wfoerstn@uni-bonn.de
 See also sugr_Line_2D, sugr_Line_2D_hom2Hes, sugr_Line_2D_hom2cen,
 sugr_Line_2D_Hes2hom, sugr_Line_2D_Hes2cen, sugr_Line_2D_cen2hom,
 sugr_get_Euclidean_Line_2D, sugr_get_centroid_Line_2D
CROSS-REFERENCE INFORMATION
This function calls:
sugr_Line_2D_Hes2cen % Uncertain centered line parameters from uncertain Hessian line parameters hes
sugr_get_Euclidean_Line_2D % Determines Hessian paramters of 2D line
This function is called by:
sugr_Homography_2D % create 2D homography
sugr_plot_Line_2D % Plot uncertain 2D line with standard hyperbola
sugr_show_Line_2D % Show/print all representations of 2D line on console
SOURCE CODE
%% Centroid representation from minimal representation
%
% [x0,p,sp,sq] = sugr_get_centroid_Line_2D(l)
%
% * l     = 2D line struct, minimal representation {l.h,l.Crr}
%
% * x0 = centroid, [x-coord. y-coord.]'
% * p  = direction of normal
% * sp = standard deviation of normal direction
% * sq = standard deviation across line
%
% Jochen Meidow, Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% See also sugr_Line_2D, sugr_Line_2D_hom2Hes, sugr_Line_2D_hom2cen,
% sugr_Line_2D_Hes2hom, sugr_Line_2D_Hes2cen, sugr_Line_2D_cen2hom,
% sugr_get_Euclidean_Line_2D, sugr_get_centroid_Line_2D
function [x0,p,sp,sq] = sugr_get_centroid_Line_2D(l)
[e,Cee]      = sugr_get_Euclidean_Line_2D(l);
[x0,p,sp,sq] = sugr_Line_2D_Hes2cen(e,Cee);