Description of init_rand_seed
Home > General-Functions > Statistics > init_rand_seed.m
init_rand_seed
PURPOSE
% init_rand_seed: initialize random number generation by specific seed
SYNOPSIS
function seed = init_rand_seed(seed)
DESCRIPTION
% init_rand_seed: initialize random number generation by specific seed
 to ensure repeatability of experiments
 seed = init_rand_seed(seed)
 seed = int, seed for initialization of rand and randn
        default 42
        if seed = 0 rand is initialized by timestamp
 Susane Wenzel 09/16
 wenzel@igg.uni-bonn.de
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fig_2_11_demo_scatter_histogram % Fig. 2.11 page 56
demo_GHM_2D_line % Demo nonlinear GHM without constraints
demo_GHM_similarity % GHM with similarity
demos_GMM_regression % test GMM with linear regression with check
fig_4_11_test_sensitivity_factors_GMM_similarity % Fig. 4.11 test sensitivity factors in GMM with similarity
demo_estimate_2D_homography_from_point_pairs % demo_estimate_2D_homography_from_point_pairs
demo_direct_plane_fit % demo plane fitting direct method
demo_estimate_Point_2D_from_Lines % demo_estimate_Point_2D_from_Lines
demo_estimate_two_symmetric_planes_from_points % test_two_symmetric_planes_from_points
demo_ALG_17_estimate_Projection_3D_2D_from_point_pairs % Demo estimate 3D projection from 2D point pairs, ALG 17
demo_estimate_Projection_3D_2D_from_point_pairs_single % Demo estimate 3D projection from 2D point pairs
demo_estimate_E_Matrix_from_point_pairs % test_estimate_E_Matrix_from_point_pairs
demo_triangulation_spherical % demo triangulation
fig_16_13_profile_reconstruction_demo_precision % Fig 16.13 page 750
fig_16_14_test_scale % Fig. 16.14 page 754
fig_16_15_symmetric_outliers % Fig. 16.15 page 755
fig_16_17_asymmetric_outliers % Fig. 16.17 page 756
fig_16_18_step_break % Fig. 15.18 page 758
fig_16_3_16_4_example_demo_profile % Fig. 16.3 page 731 and 16.4 page 732
test_smooth_dem_robust_bilinear % test dem smoothing
test_smooth_dem_robust_bilinear_square % test dem smoothing
eq_15_120_theoretical_accuracy % eq_15_120_theoretical accuracy
fig_16_20_demo_surface_reconstruction % Fig. 16.20 page 761
fig_16_21_quality_surface_reconstruction % Fig. 16.21 theoretical quality of surface reconstruction
fig_16_22_demo_robust_surface_reconstruction % Fig. 16.22 page 762
fig_16_23_aurelo_result % Fig. 16.23 page 764
fig_16_9b_demo_surface_reconstruction % Fig. 16.9 bottom page 740
SOURCE CODE
%% init_rand_seed: initialize random number generation by specific seed
% to ensure repeatability of experiments
%
% seed = init_rand_seed(seed)
% seed = int, seed for initialization of rand and randn
%        default 42
%        if seed = 0 rand is initialized by timestamp
%
% Susane Wenzel 09/16
% wenzel@igg.uni-bonn.de
function seed = init_rand_seed(seed)
if nargin<1
    seed = 42;
end
if seed == 0
    seed =  round( sum(10000*clock) );
end;
disp(['Random seed = ', num2str(seed)])
if verLessThan('matlab', '15')
    rand('state',seed); %#ok<*RAND>
    randn('state',seed);
else
    rng(seed,'v5uniform');
end