Description of rand_gauss
Home > General-Functions > Statistics > rand_gauss.m
rand_gauss
PURPOSE
% random numbers following a multivariate Gaussian with
SYNOPSIS
function ret = rand_gauss(mu, C, n)
DESCRIPTION
% random numbers following a multivariate Gaussian  with
 mean vector mu and covariance matrix C, considering correlations and
 potential singularities in C
 ret = rand_gauss(mu, C, n)
 mu  = double dx1, mean vector of dimension d
 C   = double dxd, covariance matrix
 n   = int, number of samples to generate
 ret = double dxn, n samples of Gaussian(Mu,C)
 author: Richard Steffen
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fig_2_11_demo_scatter_histogram % Fig. 2.11 page 56
fig_2_9_simulate_hom_profiles_gaussian % Fig. 2.9 page 51 and Fig 16.11 page 742
demo_GHM_2D_line % Demo nonlinear GHM without constraints
generate_points_on_plane % generate_points_on_plane(r,A);
demo_selection_X_on_Li % test whether selection is necessary when using L through X constraint
fig_16_11_simulate_inhom_profiles_gaussian % Fig. 2.9 page 51 and Fig 16.11 page 742
SOURCE CODE
%% random numbers following a multivariate Gaussian  with
% mean vector mu and covariance matrix C, considering correlations and
% potential singularities in C
%
% ret = rand_gauss(mu, C, n)
%
% mu  = double dx1, mean vector of dimension d
% C   = double dxd, covariance matrix
% n   = int, number of samples to generate
% ret = double dxn, n samples of Gaussian(Mu,C)
%
% author: Richard Steffen
function ret = rand_gauss(mu, C, n)
% Zerlegung in eigenvectoren und Eigenwerte
[R,S] = eig(full(C));
% Eigenvektoren skalieren mit Eigenwerten
A = R .* repmat(sqrt(abs(diag(S)))',length(S),1);
ret = repmat(mu,1,n) + A*randn(length(mu),n);