Description of sugr_minimal_vector
Home > General-Functions > SUGR > General > Statistics > sugr_minimal_vector.m
sugr_minimal_vector
PURPOSE
% generate minimal representation for homogeneous vector
SYNOPSIS
function xs = sugr_minimal_vector(x,Cxx)
DESCRIPTION
% generate minimal representation for homogeneous vector
 xs = sugr_minimal_vector(x,Cxx)
 * x    uncertain homogeneous vector
 * Cxx  covariance matrix
 * xs =
 * .h     spherically normalized
 * .Crr   reduced CovM
 * .Jr    Jacobian xr -> xs
 Wolfgang Förstner 1/2011
 wfoerstn@uni-bonn.de
 See also sugr_minimal_3D_Line
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sugr_Line_2D % create homogeneous 2D line
sugr_minimal_3D_Line % generate minimal representation for 3D homogeneous line
sugr_Plane % Create Plane
sugr_Point_2D % Create 2D point
sugr_construct_footpoint_xl_Point_2D % Foot point from Point_2D x onto line l
sugr_Point_3D % Create 3D point
sugr_minimal_Point_Projection_3D_2D % Minimal representation of Projection P 3D-->2D
SOURCE CODE
%% generate minimal representation for homogeneous vector
%
% xs = sugr_minimal_vector(x,Cxx)
%
% * x    uncertain homogeneous vector
% * Cxx  covariance matrix
% * xs =
% * .h     spherically normalized
% * .Crr   reduced CovM
% * .Jr    Jacobian xr -> xs
%
% Wolfgang Förstner 1/2011
% wfoerstn@uni-bonn.de
%
% See also sugr_minimal_3D_Line
function xs = sugr_minimal_vector(x,Cxx)
n      = norm(x);             % norm
xs.h   = x/n;                 % spherical normalization
Jr     = null(xs.h');         % Jacobian xr -> xs
Crr    = Jr' * Cxx * Jr/n^2;  % CovM of reduced vector
xs.Crr = Crr;                 % Crr
xs.Jr  = Jr;