Description of adjunctMatrix
Home > General-Functions > Maths > adjunctMatrix.m
adjunctMatrix
PURPOSE
% determines adjunct matrix for a square matrix
SYNOPSIS
function B = adjunctMatrix(A)
DESCRIPTION
% determines adjunct matrix for a square matrix
 B = adjunctMatrix(A)
 inv(A) = adj(A)/det(A)   holds.
   d det(A)/ dA = adj(A)'   holds.
 author:  J. Meidow, FGAN-FOM
 $Log: adj.m,v $
 Revision 1.1  2007/09/26 06:33:52  meidow
 *** empty log message ***
 adapted Wolfgang Foerstner 1/2011
 wfoerstn@uni-bonn.de
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
example_p_579_relative_orientation_mirror % test mirror image
cofactorMatrix % cofactor of a square matrix
sugr_estimate_F_and_epipoles_algebraically % Algebraic estimate F-matrix and epipoles: from n > 7 points
sugr_plot_Point_2D % Plot 2D point with standard ellipse
SOURCE CODE
%% determines adjunct matrix for a square matrix
%
% B = adjunctMatrix(A)
%
% inv(A) = adj(A)/det(A)   holds.
%   d det(A)/ dA = adj(A)'   holds.
%
% author:  J. Meidow, FGAN-FOM
%
% $Log: adj.m,v $
% Revision 1.1  2007/09/26 06:33:52  meidow
% *** empty log message ***
%
% adapted Wolfgang Foerstner 1/2011
% wfoerstn@uni-bonn.de
function B = adjunctMatrix(A)
B = zeros(size(A));
for i=1:size(A,1)
    idx_i = setdiff( 1:size(A,1), i);
    for j=1:size(A,2)
        idx_j = setdiff( 1:size(A,2),j);
        B(i,j) = (-1)^(i+j)*det(A(idx_j,idx_i));
    end
end