Description of sugr_uncondition_Projection
Home > General-Functions > SUGR > Projection_3D_2D > sugr_uncondition_Projection.m
sugr_uncondition_Projection
PURPOSE
% Uncondition Projection
SYNOPSIS
function P = sugr_uncondition_Projection(Pc, Ml, Mr)
DESCRIPTION
% Uncondition Projection
 P = sugr_uncondition_Projection(Pc, Ml, Mr)
 Pc = struct, projection conditioned
      Pc.P   3 x 4-matrix
      Pc.Crr reduced CovM
 Ml = 3 x 3 condition matrix
 Mr = 4 x 4 condition matrix
 P  = struct, unconditioned matrix P = inv(Ml) * Pc * Mr,
 Wolfgang Förstner 2/2013
 wfoerstn@uni-bonn.de
 See also sugr_condition_Points
CROSS-REFERENCE INFORMATION
This function calls:
sugr_Projection_3D_2D % Create pose
This function is called by:
sugr_estimation_algebraic_Projection_3D_2D_from_point_pairs % Algebraic estimate of Projection from corresponding 3D-2D point pairs
sugr_estimation_ml_Projection_3D_2D_from_point_pairs % ML estimate of Projection from corresponding 3D-2D point pairs
sugr_estimation_ml_Projection_3D_2D_from_point_pairs_hnh % ML estimate of Projection from corresponding 3D-2D point pairs
SOURCE CODE
%% Uncondition Projection
%
% P = sugr_uncondition_Projection(Pc, Ml, Mr)
%
% Pc = struct, projection conditioned
%      Pc.P   3 x 4-matrix
%      Pc.Crr reduced CovM
% Ml = 3 x 3 condition matrix
% Mr = 4 x 4 condition matrix
%
% P  = struct, unconditioned matrix P = inv(Ml) * Pc * Mr,
%
% Wolfgang Förstner 2/2013
% wfoerstn@uni-bonn.de
%
% See also sugr_condition_Points
function P = sugr_uncondition_Projection(Pc, Ml, Mr)
% Matrix
Pmc = Pc.P;
% unconditioned matrix
Pm =  inv(Ml) * Pmc * Mr;                                                  %#ok<MINV>
% Pm_unconditioned = Pm;
% uncondition CovM
pc  = Pmc(:);
p   = Pm(:);
% dpu    =                    (Mr' kron inv(Ml)) * dpc
% dp_r   =          J'(dp') * (Mr' kron inv(Ml)) * J(pc') dpc_r
% dp_h   = J(dp') * J'(dp') * (Mr' kron inv(Ml)) * J(pc') dpc_r
J = null(p') * null(p')' * kron(Mr',inv(Ml)) * null(pc');
Chh = J * Pc.Crr * J';
P = sugr_Projection_3D_2D(Pm,Chh);