Description of sugr_condition_Points
Home > General-Functions > SUGR > General > Estimation > sugr_condition_Points.m
sugr_condition_Points
PURPOSE
% condition points, determine conditioning matrix
SYNOPSIS
function [xc,M] = sugr_condition_Points(x)
DESCRIPTION
% condition points, determine conditioning matrix
 [xc,M] = sugr_condition_Points(x)
 x  = struct, unconditioned points, non-homogeneous coordinates
      x.e = coordiantes, Cartesian
      x.Cee = covariance matrices
 xc = struxt: conditioned SURG-points
      x.h   = homogeneous coordiantes
      x.Crr = covariance matrices of reduced coordiantes
      x.e   = nonhomogeneous coordiante
      x.Cee = covariance matrices of x.e
 M  = matrix of conditioning
 see PCV (6.137), but sigma*sqrt(dim) instead of max
 Wolfgang Förstner 2/2013
 wfoerstn@uni-bonn.de
CROSS-REFERENCE INFORMATION
This function calls:
sugr_Point_2D % Create 2D point
sugr_Point_3D % Create 3D point
This function is called by:
sugr_estimation_algebraic_Projection_3D_2D_from_point_pairs % Algebraic estimate of Projection from corresponding 3D-2D point pairs
sugr_estimation_ml_Projection_3D_2D_from_point_pairs % ML estimate of Projection from corresponding 3D-2D point pairs
sugr_estimation_ml_Projection_3D_2D_from_point_pairs_hnh % ML estimate of Projection from corresponding 3D-2D point pairs
SOURCE CODE
%% condition points, determine conditioning matrix
%
% [xc,M] = sugr_condition_Points(x)
%
% x  = struct, unconditioned points, non-homogeneous coordinates
%      x.e = coordiantes, Cartesian
%      x.Cee = covariance matrices
%
% xc = struxt: conditioned SURG-points
%      x.h   = homogeneous coordiantes
%      x.Crr = covariance matrices of reduced coordiantes
%      x.e   = nonhomogeneous coordiante
%      x.Cee = covariance matrices of x.e
% M  = matrix of conditioning
%
% see PCV (6.137), but sigma*sqrt(dim) instead of max
%
% Wolfgang Förstner 2/2013
% wfoerstn@uni-bonn.de
function [xc,M] = sugr_condition_Points(x)
% number and dimension
[N,d] = size(x.e);
xc    = x;
% mean and scale
xm = mean(x.e);
C  = cov(x.e);
sigma = sqrt(d) * sqrt(trace(C)/d);
% conditioning-matrix
M = [eye(d)       -xm';...
     zeros(1,d) sigma];
%M= eye(d+1);
% condition point coordiantes
for n=1:N
    xhn   = [x.e(n,:) , 1]';      % homogeneous coord.
    Chhn  = [squeeze(x.Cee(n,:,:)) zeros(d,1); zeros(1,d+1)];
    xcn   = M * xhn;               % homogeneous condit. coord.
    Chhcn = M * Chhn * M';         % ... CovM
    if d ==2
        xen = sugr_Point_2D(xcn,Chhcn);
    else
        xen = sugr_Point_3D(xcn,Chhcn);
    end
    xc.h(n,:)     = xen.h';        % spherically normalized cond. coord.
    xc.Crr(n,:,:) = xen.Crr;       % ... reduced CovM
    xc.e(n,:)     = xcn(1:d)/xcn(d+1);
    xc.Cee(n,:,:) = x.Cee(n,:,:)/sigma^2;
end
%  cond_x  = cond(cov(x.e))
%  cond_xc = cond(cov(xc.h(:,1:d)./(xc.h(:,d+1)*ones(1,d))))