Description of sugr_get_CovM_homogeneous_Vector
Home > General-Functions > SUGR > General > Estimation > sugr_get_CovM_homogeneous_Vector.m
sugr_get_CovM_homogeneous_Vector
PURPOSE
% get CovM of homogeneous vector x.h
SYNOPSIS
function Chh = sugr_get_CovM_homogeneous_Vector(x)
DESCRIPTION
% get CovM of homogeneous vector x.h
 Chh = sugr_get_CovM_homogeneous_Vector(x);
 * x =  struct, homogeneous object, minimal representation {x.h,x.Crr}
 * Chh = full cov. matrix of homogeneous element x.h
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sugr_distance_angular_2D % Angular distance of two 2D entities
sugr_transform_with_Homography_2D % transform uncertain elements using a projective mapping
sugr_Line_2D_hom2Hes % Uncertain Hessian line from homogeneous line
sugr_construct_join_Line_2D % Construct 2D line joining two points x and y
sugr_construct_midline_Line_2D % Construct midline of two 2D points x and y
sugr_construct_parallel_lO_Line_2D % Construct line parallel to line l through origin
sugr_construct_parallel_lx_Line_2D % Construct 2D line parallel to line l through point x
sugr_perturb_Lines_2D % Perturbes given image lines through one point
sugr_plot_Line_2D % Plot uncertain 2D line with standard hyperbola
sugr_show_Line_2D % Show/print all representations of 2D line on console
sugr_construct_join_Line_3D % calculate line from two statistically independent points
sugr_construct_footpoint_Ol_Point_2D % Foot point from 2D origin O to uncertain line l
sugr_construct_footpoint_xl_Point_2D % Foot point from Point_2D x onto line l
sugr_construct_intersection_Point_2D % Intersection 2D point two lines l and m
sugr_construct_midpoint_Point_2D % Mid point of two 2D points
sugr_plot_Point_2D % Plot 2D point with standard ellipse
sugr_show_Point_2D % Show information of 2D point on console
sugr_show_Point_3D % Show information of 3D point on console
SOURCE CODE
%% get CovM of homogeneous vector x.h
%
% Chh = sugr_get_CovM_homogeneous_Vector(x);
%
% * x =  struct, homogeneous object, minimal representation {x.h,x.Crr}
%
% * Chh = full cov. matrix of homogeneous element x.h
% see PCV (10.28)
%
% Wolfgang Förstner 2016-09-02
% wfoerstn@uni-bonn.de
function Chh = sugr_get_CovM_homogeneous_Vector(x)
J = null(x.h');        % d x (d-1)
Chh = J * x.Crr * J';