Description of sugr_ghm_update_vector
Home > General-Functions > SUGR > General > Estimation > sugr_ghm_update_vector.m
sugr_ghm_update_vector
PURPOSE
% GHM update spherically normalized vector
SYNOPSIS
function xu = sugr_ghm_update_vector(x,p)
DESCRIPTION
% GHM update spherically normalized vector
 xu = sugr_ghm_update_vector(x,p)
 * x = N-vector, approximate values
 * p = (N-1)-vector, reduced corrections
 xu = updated vector
 Wolfgang Förstner 03/2011
 wfoerstn@uni-bonn.de
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_estimate_two_symmetric_planes_from_points % test_two_symmetric_planes_from_points
sugr_estimation_ml_E_Matrix_from_point_pairs % ML estimation of E-Matrix from point pairs
sugr_estimation_ml_Homography_2D_from_point_pairs % ML estimate of 2D homography from point pairs
sugr_estimation_ml_Plane_from_points % ML estiamte of plane from points
sugr_estimation_ml_symmetric_Planes_from_points % ML estiamte of plane from points
sugr_estimation_ml_Point_2D_from_Lines % ML estimate of intersection Point_2D from N Lines_2D
sugr_perturb_2D_point_pairs_spherical % Perturb sampled 2D points pairs sphericaly
sugr_estimation_ml_Projection_3D_2D_from_point_pairs % ML estimate of Projection from corresponding 3D-2D point pairs
sugr_estimation_ml_Projection_3D_2D_from_point_pairs_hnh % ML estimate of Projection from corresponding 3D-2D point pairs
SOURCE CODE
%% GHM update spherically normalized vector
%
% xu = sugr_ghm_update_vector(x,p)
%
% * x = N-vector, approximate values
% * p = (N-1)-vector, reduced corrections
%
% xu = updated vector
%
% Wolfgang Förstner 03/2011
% wfoerstn@uni-bonn.de
function xu = sugr_ghm_update_vector(x,p)
% Update in tangent space
xu = x + null(x') * p;
% normalize
xu = xu / norm(xu);