Description of sugr_cov_matr_X
Home > General-Functions > SUGR > Triangulation > sugr_cov_matr_X.m
sugr_cov_matr_X
PURPOSE
% determine CovM for triangulated point (cov_matr_X)
SYNOPSIS
function X_est = sugr_cov_matr_X(X,sigma,est_u,est_w,rs)
DESCRIPTION
% determine CovM for triangulated point (cov_matr_X)
 determine CovM from estimated directions and 3D point
 following PCV (13.268)
 directions are assumed to follwo epipolar constraint
 X_est = sugr_cov_matr_X(X,sigma,est_u,est_w,rs)
 X           = 4x1 homgeneous vector, spherically normaized
 sigma        = standard deviation of directions, isotropic
 est_u,       = estimated directions in first camera system
 est_w        = est_v in first camera system, w=R'*v
 rs           = 2x1 vector of relative distances
 X_est        3D struct of point
 *     .h     = Xs
 *     .Crr   = CovM of reduced spherically homogeneous point coordinates
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
CROSS-REFERENCE INFORMATION
This function calls:
calc_S % skew matrix of 3-vector
sugr_Point_3D % Create 3D point
This function is called by:
sugr_triangulate_two_spherical_cameras % sugr_triangulate_two_spherical_cameras
SOURCE CODE
%% determine CovM for triangulated point (cov_matr_X)
%
% determine CovM from estimated directions and 3D point
% following PCV (13.268)
% directions are assumed to follwo epipolar constraint
%
% X_est = sugr_cov_matr_X(X,sigma,est_u,est_w,rs)
%
% X           = 4x1 homgeneous vector, spherically normaized
% sigma        = standard deviation of directions, isotropic
% est_u,       = estimated directions in first camera system
% est_w        = est_v in first camera system, w=R'*v
% rs           = 2x1 vector of relative distances
%
% X_est        3D struct of point
% *     .h     = Xs
% *     .Crr   = CovM of reduced spherically homogeneous point coordinates
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
function X_est = sugr_cov_matr_X(X,sigma,est_u,est_w,rs)
% determine basis
nv = calc_S(est_u)*est_w;
nv = nv/norm(nv);
rv = calc_S(nv)*est_u;
sv = calc_S(nv)*est_w;
C =  [inv(rv*rv'/rs(1)^2+sv*sv'/rs(2)^2+ ...
       nv*nv'*(rs(1)^2+rs(2)^2)/(rs(1)^2*rs(2)^2)+eye(3)*10^(-12)...
       )*sigma^2 ...
       zeros(3,1); [0,0,0,0]];                                              %#ok<MINV>
X_est = sugr_Point_3D(X,C);