Description of sugr_get_CovM_homogeneous_Homography_2D
Home > General-Functions > SUGR > Homography_2D > sugr_get_CovM_homogeneous_Homography_2D.m
sugr_get_CovM_homogeneous_Homography_2D
PURPOSE
% Covariance matrix of homogeneous homography,
SYNOPSIS
function [Chh,Jrh] = sugr_get_CovM_homogeneous_Homography_2D(H)
DESCRIPTION
% Covariance matrix of homogeneous homography,
 wrt h = vec(H)
 Chh = sugr_get_CovM_homogeneous_Homography_2D(H)
 Jrh = Jacobian r -> h
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 wf 2/2011
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sugr_estimation_ml_Homography_2D_from_point_pairs % ML estimate of 2D homography from point pairs
sugr_get_Euclidean_Homography_2D % Euclideanly normalized 2D homography
sugr_transform_Homography_2D % transform uncertain homography with crisp transformations
sugr_transform_with_Homography_2D % transform uncertain elements using a projective mapping
SOURCE CODE
%% Covariance matrix of homogeneous homography,
% wrt h = vec(H)
%
% Chh = sugr_get_CovM_homogeneous_Homography_2D(H)
% Jrh = Jacobian r -> h
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% wf 2/2011
function [Chh,Jrh] = sugr_get_CovM_homogeneous_Homography_2D(H)
Ht  = H.H';
Jrh = [Ht(1,1)*eye(3), ...
       Ht(1,2)*eye(3), ...
       Ht(1,3)*eye(3); ...
       Ht(2,1)*eye(3), ...
       Ht(2,2)*eye(3), ...
       Ht(2,3)*eye(3); ...
       Ht(3,1)*eye(3), ...
       Ht(3,2)*eye(3), ...
       Ht(3,3)*eye(3)] ...
       * [eye(8); [-1,0,0,0,-1,0,0,0]]; % Jacobian h -> hr , 9 x 8
Chh = Jrh * H.Crr * Jrh';               % CovM of homogeneous vector vec H