Description of sugr_show_Homography_2D
Home > General-Functions > SUGR > Homography_2D > sugr_show_Homography_2D.m
sugr_show_Homography_2D
PURPOSE
% sugr_show_Homography_2D(H)
SYNOPSIS
function sugr_show_Homography_2D(H)
DESCRIPTION
% sugr_show_Homography_2D(H)
 show elements of homography
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 wf 1/2011
CROSS-REFERENCE INFORMATION
This function calls:
sugr_get_Euclidean_Homography_2D % Euclideanly normalized 2D homography
sugr_get_chirality_Homography_2D % etermines chirality of quasi affine homography (within disk)
sugr_get_isaffine_Homography_2D % Test whether homography is affine
sugr_get_isquasiaffine_Homography_2D % Test whether homography is quasi affine
This function is called by:
SOURCE CODE
%% sugr_show_Homography_2D(H)
%
% show elements of homography
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% wf 1/2011
function sugr_show_Homography_2D(H)
[He,~] = sugr_get_Euclidean_Homography_2D(H);
He    = He
detH  = det(H.H)
isquasiaffine = sugr_get_isquasiaffine_Homography_2D(H)
isaffine      = sugr_get_isaffine_Homography_2D(H)
chi           = sugr_get_chirality_Homography_2D(H)