Description of sugr_minimal_Homography_2D
Home > General-Functions > SUGR > Homography_2D > sugr_minimal_Homography_2D.m
sugr_minimal_Homography_2D
PURPOSE
% minimal representation of homography
SYNOPSIS
function [H,Jrh] = sugr_minimal_Homography_2D(Ha,Chh)
DESCRIPTION
% minimal representation of homography
 i.e., spectrally normalize uncertain homography
 [H,Jhr] = sugr_minimal_Homography_2D(Ha,Chh)
 * Ha     uncertain regular homography
 * Chh    covariance matrix of vec Ha
 H      minimal representation:
 * .H     homography matrix, sprectrally normalized
 * .Crr   covariance matrix of vector of left differential factor
 Jrh      Jacobian dr/dh, h -> r
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 wf 3/2011
CROSS-REFERENCE INFORMATION
This function calls:
sugr_get_Jacobian_Jrh_Homography_2D % Get Jacobian Jrh dr/dh for estimating 2D Homography
This function is called by:
sugr_Homography_2D % create 2D homography
sugr_estimation_ml_Homography_2D_from_point_pairs % ML estimate of 2D homography from point pairs
sugr_plot_Homography_2D % plot uncertain homography 2D
SOURCE CODE
%% minimal representation of homography
% i.e., spectrally normalize uncertain homography
%
% [H,Jhr] = sugr_minimal_Homography_2D(Ha,Chh)
%
% * Ha     uncertain regular homography
% * Chh    covariance matrix of vec Ha
%
% H      minimal representation:
% * .H     homography matrix, sprectrally normalized
% * .Crr   covariance matrix of vector of left differential factor
%
% Jrh      Jacobian dr/dh, h -> r
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% wf 3/2011
function [H,Jrh] = sugr_minimal_Homography_2D(Ha,Chh)
det_H  = abs(det(Ha));              % positiv determinant
factor = det_H^(-1/3);              % normalizing factor
H.H    = Ha  * factor;              % normalization: det = +-1
Chh    = Chh * factor^2;
% Jhr    % Jacobian J: h->r
Jrh = sugr_get_Jacobian_Jrh_Homography_2D(H.H);
H.Crr  = Jrh * Chh * Jrh';           % CovM of reduced vector
H.type = 20;