Description of sugr_transform_Homography_2D
Home > General-Functions > SUGR > Homography_2D > sugr_transform_Homography_2D.m
sugr_transform_Homography_2D
PURPOSE
% transform uncertain homography with crisp transformations
SYNOPSIS
function H = sugr_transform_Homography_2D(H0,Tl,Tr)
DESCRIPTION
% transform uncertain homography with crisp transformations
 H = sugr_transform_Homography_2D(H0,Tl,Tr);
 H = Tl * H0 * Tr
 Wolfgang Förstner
 wfoerstn@uni-bonn.de
 wf 3/2011
CROSS-REFERENCE INFORMATION
This function calls:
sugr_Homography_2D % create 2D homography
sugr_get_CovM_homogeneous_Homography_2D % Covariance matrix of homogeneous homography,
This function is called by:
determine_Homography_2D_from_two_images demo_h_determine_homography_from_two_images: read/interactively determine homography
SOURCE CODE
%% transform uncertain homography with crisp transformations
%
% H = sugr_transform_Homography_2D(H0,Tl,Tr);
%
% H = Tl * H0 * Tr
%
% Wolfgang Förstner
% wfoerstn@uni-bonn.de
%
% wf 3/2011
function H = sugr_transform_Homography_2D(H0,Tl,Tr)
% homography
Ht = Tl * H0.H * Tr;
% covariance matrix
C0hh = sugr_get_CovM_homogeneous_Homography_2D(H0);
J = kron(Tr', Tl);
Chh = J * C0hh *J';
% generate struct
H = sugr_Homography_2D(Ht,Chh);